### ISSUE TITLE
MODELE_FLIPPER does not update changes, only additions.

### ISSUE THREAD

**Issue by e5ky0** [BinetLoisir/FlipperFinderApp#14]
I rectified a few typing mistakes in the MOFL_NAME field in the database class MODELE_FLIPPER. mistakes like " instead of ' . They are not taken into account when updating.

The list of flipper models does update when a new pinball model is added but a modification on a old one is not taken into account.

**Comment by Cimbali** [comment]
Il y a pas de champ "date" donc j'imagine que la bdd met pas à jour les modèles (parce qu'elle voit pas qu'il y en a).
Pour confirmer: si tu supprimes totue les données de l'appli ça devrait forcer un retéléchagement de la bdd. Ça devrait recharger les modèles.

Comme solutions: on peut forcer le re-téléchargement des modèles à chaque màj, sinon on peut versionner comme sur les autres tables.

**Comment by e5ky0** [comment]
OK, en faisant un Clear Data de l'appli, ça m'a bien fait un retéléchargement.
Les derniers flips ajoutés (Ghostbusters...) ont bien le bon nom.
Par contre des flips anciens (comme Tee'd Off, ne sont pas mis à jour) et ont gardé le "

J'ai l'impression que l'appli est installée avec une Base Locale qui date un peu, (i.e. les fichiers JSON qui sont dans /asset)  le dernier commentaire dedans date du 26/10/2015.

Et la Maj ne semble mettre à jour uniquement les nouveaux items et ceux possédant un champ DateMaj.

- Pourrait-on utiliser le champ automatique UpdatedAt pour détecter une modif sur les modèles de Flip?
- Sinon on peut régler le Pb en mettant a jour les JSON dans assets lors de la prochaine version de l'app.

**Comment by e5ky0** [comment]
solved in solved-update-pb branch
